### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Gargo** [horitaku46/BlowinSwiper#2]
http://gargo.of.by/blowinswiper/

I have translated your readme to Russian. Add a link to the translation on my website please

**Comment by horitaku46** [comment]
Thank you for translating this readme into Russian!
I attached a link!🙇‍♂️
https://github.com/horitaku46/BlowinSwiper/commit/2c2bff1e82f6fe19dd0ac5331657bf9f35d89e6a
